apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastalert
  name: elastalert
spec:
  ports:
  - port: 3030
    protocol: TCP
    targetPort: 3030
    name: "http"
  - port: 3333
    protocol: TCP
    targetPort: 3333
    name: "ws"
  selector:
    app: elastalert
